language: java
jdk:
  - openjdk7
  - openjdk6

env:
  global:
    - secure: "VgUhs+4iS0ASQZCsogNd7eXkU4oO7c+X/Vkb4/4loZHVsICfSlCYuJBGgKLgDRxE3LrIBNHx+FFYQot9W0hWlPRWFEG0kWWb359jG3d8qys2Jg/vit2iyqoEu5O4Q552Ez5/uHBRMShH732HRL37DrPSSpXWkJpzJpsoKlpiSw8="
  
matrix:
  include:
    - jdk: oraclejdk7
      after_success: "mvn jacoco:report coveralls:jacoco"
    - jdk: oraclejdk7
      script: mvn verify
      env: PLATFORM=WIN8
    - jdk: oraclejdk7
      script: mvn verify
      env: PLATFORM=LINUX
